apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-shell
  template:
    metadata:
      labels:
        app: vuln-shell
    spec:
      containers:
      - name: vuln-shell
        image: your-dockerhub-username/vulnerable-shell-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vuln-shell-service
spec:
  type: NodePort
  selector:
    app: vuln-shell
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
